name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print root directory
        run: ls -l
      - name: Print monorepo.template directory (if exists)
        run: |
          if [ -d "monorepo.template" ]; then ls -l monorepo.template; fi
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: monorepo.template
      - name: Lint
        run: pnpm lint
        working-directory: monorepo.template
      - name: Typecheck
        run: pnpm typecheck
        working-directory: monorepo.template
      - name: Build
        run: pnpm build
        working-directory: monorepo.template
      - name: Test
        run: pnpm test
        working-directory: monorepo.template
